# Generated by Django 4.0.1 on 2022-04-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_info_diet_plan_user_info_exercise_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='diet_plan',
        ),
    ]
