# Generated by Django 4.0.1 on 2022-04-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_info_diet_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='exercise_plan',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='username',
        ),
    ]
